version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: '256mb'
    command: "postgres -c max_wal_size=2GB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SHM_SIZE: 256m